<?xml version="1.0" encoding="UTF-8"?>CREATE TABLE IF NOT EXISTS climate_terms (id INTEGER PRIMARY KEY, climate_term TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS debates (id INTEGER PRIMARY KEY, date TEXT NOT NULL, sitting_number TEXT, legislative_period TEXT);
CREATE TABLE IF NOT EXISTS speaker (id TEXT PRIMARY KEY, first_name TEXT, last_name TEXT, party_affiliation TEXT, sex TEXT);
CREATE TABLE IF NOT EXISTS quotes (id INTEGER PRIMARY KEY, quote TEXT NOT NULL, debates_id INTEGER NOT NULL, speaker_id TEXT NOT NULL, FOREIGN KEY (debates_id) REFERENCES debates(id), FOREIGN KEY (speaker_id) REFERENCES speaker(id));
CREATE TABLE IF NOT EXISTS quotes_climate_terms (id INTEGER PRIMARY KEY, quotes_id INTEGER NOT NULL, climate_terms_id INTEGER NOT NULL, FOREIGN KEY (quotes_id) REFERENCES quotes(id), FOREIGN KEY (climate_terms_id) REFERENCES climate_terms(id));

INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (1, 'Ausstoß');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (2, 'Bio');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (3, 'Brennstoff');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (4, 'Climate');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (5, 'CO2');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (6, 'Dürre');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (7, 'Emission');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (8, 'Energieeffizienz');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (9, 'Energieträger');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (10, 'Energiewende');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (11, 'Erneuerbar');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (12, 'Erderwärmung');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (13, 'Green');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (14, 'Hitzewelle');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (15, 'Karbon');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (16, 'Kipppunkt');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (17, 'Klima');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (18, 'Kohlendioxid');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (19, 'Kreislaufwirtschaft');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (20, 'Lebensraum');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (21, 'Methan');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (22, 'Natur');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (23, 'Ökologisch');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (24, 'Ökosystem');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (25, 'Pariser Abkommen');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (26, 'Recycling');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (27, 'Ressource');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (28, 'Rohstoff');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (29, 'Temperatur');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (30, 'Treibhaus');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (31, 'Umwelt');
INSERT OR IGNORE INTO climate_terms (id, climate_term) VALUES (32, 'Überschwemmung');